### ISSUE TITLE
PHP error with plugin human resource

### ISSUE THREAD

**Issue by amma35** [pluginsGLPI/useditemsexport#11]
PHP error when generating pdf with linked elements without a serial number (example: human resource, ...)

`  *** PHP Notice(8): Undefined index: serial
  Backtrace :
  plugins/useditemsexport/inc/export.class.php:326   
  plugins/resources/front/export.pdf.php:16          PluginUseditemsexportExport::generatePDF()`

**Comment by flegastelois** [comment]
Merged.
