### ISSUE TITLE
PHP error

### ISSUE THREAD

**Issue by tabad** [pluginsGLPI/useditemsexport#28]
## The environment

  * GLPI v9.2.3
    * Used Item Export v2.0.0

More information about the environment [here](https://github.com/pluginsGLPI/useditemsexport/files/1982538/ilab-server-information.txt).

## The issue

   The file `php-errrors.log` contains the following entry.

```text
[root@ilab glpi]# cat php-errors.log 
2018-05-08 08:08:58 [@ilab.sescam.jclm.es]
  From Plugin::getInfo() in /usr/local/share/glpi/inc/plugin.class.php line 1374
  plugin_version_useditemexport method must be defined! 
```

Regards,

**Comment by flegastelois** [comment]
Hi,

How did you install the plugin in the corresponding folder of GLPI? 

I think you put a bad name directory "useditemexport" instead of "useditem**s**export" (which is the official name).

Regards,

**Comment by tabad** [comment]
Hello @flegastelois,

Well, I just install the plugin from the `tar.bz2` file.

```bash
~$  wget https://github.com/pluginsGLPI/useditemsexport/releases/download/2.0.0/glpi-useditemexport-2.0.0.tar.bz2
~$ tar -jtvf glpi-useditemexport-2.0.0.tar.bz2
drwxrwxr-x francois/francois 0 2018-02-20 15:11 useditemexport/
drwxrwxr-x francois/francois 0 2018-02-20 15:05 useditemexport/screenshots/
-rw-rw-r-- francois/francois 64560 2018-02-20 15:05 useditemexport/screenshots/fr_useditemsexport-tab.png
-rw-rw-r-- francois/francois   348 2018-02-20 15:05 useditemexport/README.md
-rw-rw-r-- francois/francois  3501 2018-02-20 15:05 useditemexport/setup.php
-rw-rw-r-- francois/francois 18046 2018-02-20 15:05 useditemexport/LICENSE
-rw-rw-r-- francois/francois   263 2018-02-20 15:05 useditemexport/composer.json
drwxrwxr-x francois/francois     0 2018-02-20 15:05 useditemexport/locales/
-rw-rw-r-- francois/francois  1465 2018-02-20 15:11 useditemexport/locales/en_GB.mo
-rw-rw-r-- francois/francois  2440 2018-02-20 15:05 useditemexport/locales/fr_FR.po
-rw-rw-r-- francois/francois  2209 2018-02-20 15:05 useditemexport/locales/en_GB.po
[...]
```

If, as you say, the official name of directory is *useditem**s**export* then the package `glpi-useditemexport-2.0.0.tar.bz2` is not created correctly, isn't it?

Following your tip, I have changed the name of the plugin directory

```bash
[root@ilab glpi]# mv plugins/useditemexport plugins/useditemsexport
[root@ilab glpi]# systemctl restart rh-php70-php-fpm.service
```

and now the error

```text
  From Plugin::getInfo() in /usr/local/share/glpi/inc/plugin.class.php line 1374
  plugin_version_useditemexport method must be defined! 
```

doesn't appear into `php-errors.log` file. It seems clear, the package `glpi-useditemexport-2.0.0.tar.bz2` is not created correctly.

Regards,

**Comment by flegastelois** [comment]
Hi @tabad,

Thank you very much for these details.

Yes, your are right, the official package doesn't match the official name as I feared :(

I used the "plugin-release" tool made by my colleague @trasher :
https://github.com/glpi-project/tools

I made an issue : https://github.com/glpi-project/tools/issues/4

And I re-upload a correct archive.

Regards,

**Comment by tabad** [comment]
Hello @flegastelois,

Thank you. I'll update my package repositories. ;)

You can close this issue when you want.

Regards,
