### ISSUE TITLE
File Not Found..

### ISSUE THREAD

**Issue by samsonikbv** [pluginsGLPI/useditemsexport#38]
File Not Found: /var/www/glpi/files/_uploads/0005-2019.pdf

not create files in directory 
img http://prntscr.com/mxtce0

but create files in directory _tmp
http://prntscr.com/mxtcxv

sorry my english

**Comment by Steve543** [comment]
Hello,

Update line 383 (file in ../glpi/plugins/useditemexport/inc/export.class.php) with: 

      // Store PDF in GLPi upload dir and create document
      //file_put_contents(GLPI_TMP_DIR . '/' . $refnumber.'.pdf', $contentPDF);
	  file_put_contents(**GLPI_UPLOAD_DIR** . '/' . $refnumber.'.pdf', $contentPDF);
      $documents_id = self::createDocument($refnumber);

**Comment by samsonikbv** [comment]
thanks!!
