### ISSUE TITLE
GLPI Used items export: Profile

### ISSUE THREAD

**Issue by janpieters74** [pluginsGLPI/useditemsexport#9]
I would like to use your plugin to allow our HR-staff to generate an overview of the equipment that was assigned to an employee when that employee is leaving the company.
Of course our HR staff cannot have other authorisations in GLPI, so I stripped the user profile so they can only Read the ‘Users’, and I allowed them to generate the “Used items Export” PDF. But when they generate the document, GLPI returns a no-Access error. What other authorisations are necessary to allow this?

**Comment by janpieters74** [comment]
With allowing the Document creation in the user profile (Management), it is possible to create the PDF.
But, since the HR-user has no rights to the assets, the document is empty. How can I manage this ? Do I have to give HR also Read-access to the whole asset list ?

**Comment by flegastelois** [comment]
Hi,

Here is the list of available rights on a **Profile**, needed to use the plugin features : 
* **Profile's interface** positionned on **Standard interface**.
* To change the plugin configuration : **Setup > General setup > UPDATE** right is needed.
* To manage specific plugin rights (**Used items export** tab on a **Profile**) : **Administration > Profiles > UPDATE** right is needed.
* To see the **Used items export** tab in a user's form : at-least one of **Used items export > READ or CREATE or PURGE** right is needed, and of course the right **Administration > Users > READ** to access them.
* To open and see the **Export document** on **Used items export** tab in a user's form : **Management > Documents > READ**.
* To correctly **Generate new export** on **Used items export** tab in a user's form : **Used items export > CREATE** + **Management > Documents > CREATE**
* To purge entry on **Used items export** tab in a user's form : **Used items export > PURGE** + **Management > Documents > PURGE**
* Foreach itemtype ('Computer', 'Monitor', 'NetworkEquipment','Peripheral', 'Phone', 'Printer', 'Software','SoftwareLicense') you want to display on report : **Assets > 'Itemtype' > READ**.

Best regards,
François
