### ISSUE TITLE
useditemsexport tab does not display page from user view

### ISSUE THREAD

**Issue by credicorzakiewicz** [pluginsGLPI/useditemsexport#92]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### GLPI Version

10.0.17

### Plugin version

2.5.1

### Bug description

After upgrading GLPI from 10.0.15 to 10.0.17, going to Administration / User, then selecting a user, clicking on "Used Items Export" tab, the load is stuck in progress (with the icon that represents the action of "loading") and the content of the page never appears.
In /var/www/glpi/files/_log/php_errors.log, I can see the following message :
[2024-12-10 13:08:21] glpiphplog.ALERT:   *** PHP Compile Error (64): Cannot redeclare twig_cycle() (previously declared in /var/www/glpi/vendor/twig/twig/src/Resources/core.php:20) i> 

Then I have downgraded to GLPI 10.0.15 and everything is working fine.

Could you please help me to make it working on GLPI 10.0.17 ?

Thank you.

**Comment by stonebuzz** [comment]
hi @credicorzakiewicz 

How did you install the plugin?

Best regards

**Comment by credicorzakiewicz** [comment]
I have not "reinstall" the plugin. I have got it already installed in the previous GLPI version then I upgraded GLPI copying back the plugins folder using this command :
sudo cp -Rf /home/glpi_adm/backup_glpi/plugins /var/www/glpi/

**Comment by stonebuzz** [comment]
hi @credicorzakiewicz

How did you install the plugin? with marketplace ? from github release ? fromgithub branch ?

Best regards

**Comment by stonebuzz** [comment]
It seems that the plugin is dev dependencies via composer ((according to the error)

**Comment by credicorzakiewicz** [comment]
> you install the plugin? with marketplace ? from github release ? fromgithub branch ?

If you mean "how it was installed initialy", I don't know as this is a legacy installation on GLPI server of my company, I have got no trace of the action performed by a guy who is not member of the company anymore.

**Comment by stonebuzz** [comment]
Simply delete the plugin from the server, remove it (clean) from the list of plugins in GLPI, then reinstall it either from the marketplace or from the latest version available on GitHub:

[**Used Items Export 2.5.2** - Archive glpi-useditemsexport-2.5.2.tar.bz2](https://github.com/pluginsGLPI/useditemsexport/releases/tag/2.5.2)

**Comment by credicorzakiewicz** [comment]
Thanks.
As our file export.class.php contains many additional lines to be able to edit customized forms, if I replace it by upgrading, we lose the customization. And of course, we will have to do it one day.
Is it possible with the plugin to put the customized part into another file so that we would be no impacted each time there is a plugin update to deploy ?

**Comment by stonebuzz** [comment]
If you are familiar with Git, you can maintain a patch or a dedicated branch to incorporate your modifications. 

However, it is not the plugin’s responsibility to preserve these changes.



Kind regards,

**Comment by credicorzakiewicz** [comment]
Your message is clear. Thanks again for your help.
